---
name: "CI pipeline"

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api_build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install -r .github/workflows/requirements.txt

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_YAML: true

      - name: Detect Secrets Dependencies
        run: |
            apt-get update && apt-get install -y jq
            pip install yq
        
      - name: Run Yelp's detect-secrets (hook)
        run: detect-secrets scan

      - name: Install {{cookiecutter.python_project}} dependencies
        working-directory: ./src/{{cookiecutter.python_project}}
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests and check code coverage
        working-directory: ./src/{{cookiecutter.python_project}}
        run: coverage run -m unittest discover -s tests 
        shell: bash
        id: codecoveragetests

      - name: Check code coverage
        working-directory: ./src/{{cookiecutter.python_project}}
        if: steps.codecoveragetests.outputs.exit_code == 0
        run: |
          coverage report --fail-under=80 --omit './tests/*'